DRFT-131 Adds AUDIT log level to app logger
RedHatInsights/kerlescan pull request #14
Opened 2021-03-04 15:31 UTC by petrblaho

Use it as `logger.audit("message")`
to see output as `[2021-02-18 15:29:43 +0000] [29] [AUDIT] message`.

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [x] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [x] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

2021-03-04 15:36 UTC, petrblaho commented
https://issues.redhat.com/browse/DRFT-131

2021-03-04 15:41 UTC, CodeHeeler approved these changes
LGTM, thanks for handling this!

2021-03-04 15:53 UTC, petrblaho commented
@CodeHeeler thank you

2021-03-04 23:02 UTC, eherget requested changes
I'm concerned we're not checking that keys "identity", "user" and "username" exist. If the x-rh-identity header ever changes or currently allows some of these to not exist, it will cause our code to crash.  Let's make sure we don't crash our code because of KeyError exceptions.

2021-03-04 23:06 UTC, eherget requested changes

2021-03-04 23:06 UTC, eherget commented on kerlescan/audit_logging.py
> +        status = "failure" if kws.pop("failure", False) else None
This requires the caller to provide success=True or failure=True.  Would it make more sense for the caller to provide just success=[True|False] and then set status = "success" or "failure" based on the value True or False?

2021-03-04 23:06 UTC, eherget commented on kerlescan/audit_logging.py
> +def audit(self, message, *args, **kws):
Can we add a comment describing what kws args that can be passed and their expected values?

2021-03-05 15:05 UTC, petrblaho commented
I hope I addressed your review notes, @eherget

2021-03-05 15:17 UTC, CodeHeeler approved these changes
Thanks, I think this addresses all the concerns that were raised.

2021-03-05 15:55 UTC, eherget approved these changes

2021-03-05 15:56 UTC, eherget commented
Looks good now, thank you!!!

2021-03-05 16:31 UTC, merged